# Generated by Django 4.1 on 2022-12-12 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DinnerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=600)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DinnerApp.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DinnerApp.menu')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DinnerApp.restaurante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DinnerApp.restaurante')),
            ],
        ),
    ]
